export interface Word {
  arabic: string;
  transliteration: string;
  uzbek: string;
  category: string;
}

export const ARABIC_ALPHABET = [
  { char: "أ", name: "Alif" }, { char: "ب", name: "Ba" }, { char: "ت", name: "Ta" }, { char: "ث", name: "Tha" },
  { char: "ج", name: "Jim" }, { char: "ح", name: "Ha" }, { char: "خ", name: "Kha" }, { char: "د", name: "Dal" },
  { char: "ذ", name: "Dhal" }, { char: "ر", name: "Ra" }, { char: "ز", name: "Zay" }, { char: "س", name: "Sin" },
  { char: "ش", name: "Shin" }, { char: "ص", name: "Sad" }, { char: "ض", name: "Dad" }, { char: "ط", name: "Ta" },
  { char: "ظ", name: "Za" }, { char: "ع", name: "Ain" }, { char: "غ", name: "Ghain" }, { char: "ف", name: "Fa" },
  { char: "ق", name: "Qaf" }, { char: "ك", name: "Kaf" }, { char: "ل", name: "Lam" }, { char: "م", name: "Mim" },
  { char: "ن", name: "Nun" }, { char: "ه", name: "Ha" }, { char: "و", name: "Waw" }, { char: "ي", name: "Ya" }
];

export const ARABIC_NUMBERS = [
  { char: "٠", val: 0, name: "Sifr" }, { char: "١", val: 1, name: "Wahid" },
  { char: "٢", val: 2, name: "Ithnan" }, { char: "٣", val: 3, name: "Thalathah" },
  { char: "٤", val: 4, name: "Arba'ah" }, { char: "٥", val: 5, name: "Khamsah" },
  { char: "٦", val: 6, name: "Sittah" }, { char: "٧", val: 7, name: "Sab'ah" },
  { char: "٨", val: 8, name: "Thamaniyah" }, { char: "٩", val: 9, name: "Tis'ah" },
  { char: "١٠", val: 10, name: "Asharah" }
];

export const QURAN_SURAHS = [
  { id: 1, name: "Al-Fatiha", arabic: "الفاتحة", verses: 7, type: "Meccan" },
  { id: 2, name: "Al-Baqarah", arabic: "البقرة", verses: 286, type: "Medinan" },
  { id: 3, name: "Al-Imran", arabic: "آل عمران", verses: 200, type: "Medinan" },
  { id: 4, name: "An-Nisa", arabic: "النساء", verses: 176, type: "Medinan" },
  { id: 5, name: "Al-Ma'idah", arabic: "المائدة", verses: 120, type: "Medinan" },
  { id: 6, name: "Al-An'am", arabic: "الأنعام", verses: 165, type: "Meccan" },
  { id: 7, name: "Al-A'raf", arabic: "الأعراف", verses: 206, type: "Meccan" },
  { id: 8, name: "Al-Anfal", arabic: "الأنفال", verses: 75, type: "Medinan" },
  { id: 9, name: "At-Tawbah", arabic: "التوبة", verses: 129, type: "Medinan" },
  { id: 10, name: "Yunus", arabic: "يونس", verses: 109, type: "Meccan" },
  { id: 11, name: "Hud", arabic: "هود", verses: 123, type: "Meccan" },
  { id: 12, name: "Yusuf", arabic: "يوسف", verses: 111, type: "Meccan" },
  { id: 13, name: "Ar-Ra'd", arabic: "الرعد", verses: 43, type: "Medinan" },
  { id: 14, name: "Ibrahim", arabic: "إبراهيم", verses: 52, type: "Meccan" },
  { id: 15, name: "Al-Hijr", arabic: "الحجر", verses: 99, type: "Meccan" },
  { id: 16, name: "An-Nahl", arabic: "النحل", verses: 128, type: "Meccan" },
  { id: 17, name: "Al-Isra", arabic: "الإسراء", verses: 111, type: "Meccan" },
  { id: 18, name: "Al-Kahf", arabic: "الكهف", verses: 110, type: "Meccan" },
  { id: 19, name: "Maryam", arabic: "مريم", verses: 98, type: "Meccan" },
  { id: 20, name: "Ta-Ha", arabic: "طه", verses: 135, type: "Meccan" },
  { id: 21, name: "Al-Anbiya", arabic: "الأنبياء", verses: 112, type: "Meccan" },
  { id: 22, name: "Al-Hajj", arabic: "الحج", verses: 78, type: "Medinan" },
  { id: 23, name: "Al-Mu'minun", arabic: "المؤمنون", verses: 118, type: "Meccan" },
  { id: 24, name: "An-Nur", arabic: "النور", verses: 64, type: "Medinan" },
  { id: 25, name: "Al-Furqan", arabic: "الفرقان", verses: 77, type: "Meccan" },
  { id: 26, name: "Ash-Shu'ara", arabic: "الشعراء", verses: 227, type: "Meccan" },
  { id: 27, name: "An-Naml", arabic: "النمل", verses: 93, type: "Meccan" },
  { id: 28, name: "Al-Qasas", arabic: "القصص", verses: 88, type: "Meccan" },
  { id: 29, name: "Al-Ankabut", arabic: "العنكبوت", verses: 69, type: "Meccan" },
  { id: 30, name: "Ar-Rum", arabic: "الروم", verses: 60, type: "Meccan" },
  { id: 31, name: "Luqman", arabic: "لقمان", verses: 34, type: "Meccan" },
  { id: 32, name: "As-Sajdah", arabic: "السجدة", verses: 30, type: "Meccan" },
  { id: 33, name: "Al-Ahzab", arabic: "الأحزاب", verses: 73, type: "Medinan" },
  { id: 34, name: "Saba", arabic: "سبأ", verses: 54, type: "Meccan" },
  { id: 35, name: "Fatir", arabic: "فاطر", verses: 45, type: "Meccan" },
  { id: 36, name: "Ya-Sin", arabic: "يس", verses: 83, type: "Meccan" },
  { id: 37, name: "As-Saffat", arabic: "الصافات", verses: 182, type: "Meccan" },
  { id: 38, name: "Sad", arabic: "ص", verses: 88, type: "Meccan" },
  { id: 39, name: "Az-Zumar", arabic: "الزمر", verses: 75, type: "Meccan" },
  { id: 40, name: "Ghafir", arabic: "غافر", verses: 85, type: "Meccan" },
  { id: 41, name: "Fussilat", arabic: "فصلت", verses: 54, type: "Meccan" },
  { id: 42, name: "Ash-Shura", arabic: "الشورى", verses: 53, type: "Meccan" },
  { id: 43, name: "Az-Zukhruf", arabic: "الزخرف", verses: 89, type: "Meccan" },
  { id: 44, name: "Ad-Dukhan", arabic: "الدخان", verses: 59, type: "Meccan" },
  { id: 45, name: "Al-Jathiyah", arabic: "الجاثية", verses: 37, type: "Meccan" },
  { id: 46, name: "Al-Ahqaf", arabic: "الأحقاف", verses: 35, type: "Meccan" },
  { id: 47, name: "Muhammad", arabic: "محمد", verses: 38, type: "Medinan" },
  { id: 48, name: "Al-Fath", arabic: "الفتح", verses: 29, type: "Medinan" },
  { id: 49, name: "Al-Hujurat", arabic: "الحجرات", verses: 18, type: "Medinan" },
  { id: 50, name: "Qaf", arabic: "ق", verses: 45, type: "Meccan" },
  { id: 51, name: "Adh-Dhariyat", arabic: "الذاريات", verses: 60, type: "Meccan" },
  { id: 52, name: "At-Tur", arabic: "الطور", verses: 49, type: "Meccan" },
  { id: 53, name: "An-Najm", arabic: "النجم", verses: 62, type: "Meccan" },
  { id: 54, name: "Al-Qamar", arabic: "القمر", verses: 55, type: "Meccan" },
  { id: 55, name: "Ar-Rahman", arabic: "الرحمن", verses: 78, type: "Medinan" },
  { id: 56, name: "Al-Waqi'ah", arabic: "الواقعة", verses: 96, type: "Meccan" },
  { id: 57, name: "Al-Hadid", arabic: "الحديد", verses: 29, type: "Medinan" },
  { id: 58, name: "Al-Mujadila", arabic: "المجادلة", verses: 22, type: "Medinan" },
  { id: 59, name: "Al-Hashr", arabic: "الحشر", verses: 24, type: "Medinan" },
  { id: 60, name: "Al-Mumtahanah", arabic: "الممتحنة", verses: 13, type: "Medinan" },
  { id: 61, name: "As-Saff", arabic: "الصف", verses: 14, type: "Medinan" },
  { id: 62, name: "Al-Jumu'ah", arabic: "الجمعة", verses: 11, type: "Medinan" },
  { id: 63, name: "Al-Munafiqun", arabic: "المنافقون", verses: 11, type: "Medinan" },
  { id: 64, name: "At-Taghabun", arabic: "التغابن", verses: 18, type: "Medinan" },
  { id: 65, name: "At-Talaq", arabic: "الطلاق", verses: 12, type: "Medinan" },
  { id: 66, name: "At-Tahrim", arabic: "التحريم", verses: 12, type: "Medinan" },
  { id: 67, name: "Al-Mulk", arabic: "الملك", verses: 30, type: "Meccan" },
  { id: 68, name: "Al-Qalam", arabic: "القلم", verses: 52, type: "Meccan" },
  { id: 69, name: "Al-Haqqah", arabic: "الحاقة", verses: 52, type: "Meccan" },
  { id: 70, name: "Al-Ma'arij", arabic: "المعارج", verses: 44, type: "Meccan" },
  { id: 71, name: "Nuh", arabic: "نوح", verses: 28, type: "Meccan" },
  { id: 72, name: "Al-Jinn", arabic: "الجن", verses: 28, type: "Meccan" },
  { id: 73, name: "Al-Muzzammil", arabic: "المزمل", verses: 20, type: "Meccan" },
  { id: 74, name: "Al-Muddaththir", arabic: "المدثر", verses: 56, type: "Meccan" },
  { id: 75, name: "Al-Qiyamah", arabic: "القيامة", verses: 40, type: "Meccan" },
  { id: 76, name: "Al-Insan", arabic: "الإنسان", verses: 31, type: "Medinan" },
  { id: 77, name: "Al-Mursalat", arabic: "المرسلات", verses: 50, type: "Meccan" },
  { id: 78, name: "An-Naba", arabic: "النبأ", verses: 40, type: "Meccan" },
  { id: 79, name: "An-Nazi'at", arabic: "النازعات", verses: 46, type: "Meccan" },
  { id: 80, name: "Abasa", arabic: "عبس", verses: 42, type: "Meccan" },
  { id: 81, name: "At-Takwir", arabic: "التكوير", verses: 29, type: "Meccan" },
  { id: 82, name: "Al-Infitar", arabic: "الانفطار", verses: 19, type: "Meccan" },
  { id: 83, name: "Al-Mutaffifin", arabic: "المطففين", verses: 36, type: "Meccan" },
  { id: 84, name: "Al-Inshiqaq", arabic: "الانشقاق", verses: 25, type: "Meccan" },
  { id: 85, name: "Al-Buruj", arabic: "البروج", verses: 22, type: "Meccan" },
  { id: 86, name: "At-Tariq", arabic: "الطارق", verses: 17, type: "Meccan" },
  { id: 87, name: "Al-A'la", arabic: "الأعلى", verses: 19, type: "Meccan" },
  { id: 88, name: "Al-Ghashiyah", arabic: "الغاشية", verses: 26, type: "Meccan" },
  { id: 89, name: "Al-Fajr", arabic: "الفجر", verses: 30, type: "Meccan" },
  { id: 90, name: "Al-Balad", arabic: "البلد", verses: 20, type: "Meccan" },
  { id: 91, name: "Ash-Shams", arabic: "الشمس", verses: 15, type: "Meccan" },
  { id: 92, name: "Al-Layl", arabic: "الليل", verses: 21, type: "Meccan" },
  { id: 93, name: "Ad-Duha", arabic: "الضحى", verses: 11, type: "Meccan" },
  { id: 94, name: "Ash-Sharh", arabic: "الشرح", verses: 8, type: "Meccan" },
  { id: 95, name: "At-Tin", arabic: "التين", verses: 8, type: "Meccan" },
  { id: 96, name: "Al-Alaq", arabic: "العلق", verses: 19, type: "Meccan" },
  { id: 97, name: "Al-Qadr", arabic: "القدر", verses: 5, type: "Meccan" },
  { id: 98, name: "Al-Bayyinah", arabic: "البينة", verses: 8, type: "Medinan" },
  { id: 99, name: "Az-Zalzalah", arabic: "الزلزلة", verses: 8, type: "Medinan" },
  { id: 100, name: "Al-Adiyat", arabic: "العاديات", verses: 11, type: "Meccan" },
  { id: 101, name: "Al-Qari'ah", arabic: "القارعة", verses: 11, type: "Meccan" },
  { id: 102, name: "At-Takathur", arabic: "التكاثر", verses: 8, type: "Meccan" },
  { id: 103, name: "Al-Asr", arabic: "العصر", verses: 3, type: "Meccan" },
  { id: 104, name: "Al-Humazah", arabic: "الهمزة", verses: 9, type: "Meccan" },
  { id: 105, name: "Al-Fil", arabic: "الفيل", verses: 5, type: "Meccan" },
  { id: 106, name: "Quraysh", arabic: "قريش", verses: 4, type: "Meccan" },
  { id: 107, name: "Al-Ma'un", arabic: "الماعون", verses: 7, type: "Meccan" },
  { id: 108, name: "Al-Kawthar", arabic: "الكوثر", verses: 3, type: "Meccan" },
  { id: 109, name: "Al-Kafirun", arabic: "الكافرون", verses: 6, type: "Meccan" },
  { id: 110, name: "An-Nasr", arabic: "النصر", verses: 3, type: "Medinan" },
  { id: 111, name: "Al-Masad", arabic: "المسد", verses: 5, type: "Meccan" },
  { id: 112, name: "Al-Ikhlas", arabic: "الإخلاص", verses: 4, type: "Meccan" },
  { id: 113, name: "Al-Falaq", arabic: "الفلق", verses: 5, type: "Meccan" },
  { id: 114, name: "An-Nas", arabic: "الناس", verses: 6, type: "Meccan" }
];

export const ARABIC_DICTIONARY: Word[] = [
  // Oilaviy (Family)
  { arabic: "أَب", transliteration: "Ab", uzbek: "Ota", category: "Oila" },
  { arabic: "أُمّ", transliteration: "Umm", uzbek: "Ona", category: "Oila" },
  { arabic: "أَخ", transliteration: "Akh", uzbek: "Aka/Uka", category: "Oila" },
  { arabic: "أُخْت", transliteration: "Ukht", uzbek: "Opa/Singil", category: "Oila" },
  { arabic: "جَدّ", transliteration: "Jadd", uzbek: "Bobo", category: "Oila" },
  { arabic: "جَدَّة", transliteration: "Jaddah", uzbek: "Buvi", category: "Oila" },
  { arabic: "اِبْن", transliteration: "Ibn", uzbek: "O'g'il", category: "Oila" },
  { arabic: "اِبْنَة", transliteration: "Ibnah", uzbek: "Qiz", category: "Oila" },
  { arabic: "زَوْج", transliteration: "Zawj", uzbek: "Er", category: "Oila" },
  { arabic: "زَوْجَة", transliteration: "Zawjah", uzbek: "Xotin", category: "Oila" },

  // Salomlashish (Greetings)
  { arabic: "سَلَام", transliteration: "Salam", uzbek: "Salom", category: "Muloqot" },
  { arabic: "مَرْحَبًا", transliteration: "Marhaban", uzbek: "Xush kelibsiz", category: "Muloqot" },
  { arabic: "شُكْرًا", transliteration: "Shukran", uzbek: "Rahmat", category: "Muloqot" },
  { arabic: "عَفْوًا", transliteration: "Afwan", uzbek: "Arzimaydi", category: "Muloqot" },
  { arabic: "نَعَمْ", transliteration: "Na'am", uzbek: "Ha", category: "Muloqot" },
  { arabic: "لَا", transliteration: "La", uzbek: "Yo'q", category: "Muloqot" },
  { arabic: "كَيْفَ حَالُكَ؟", transliteration: "Kayfa haluka?", uzbek: "Ahvolingiz qanday?", category: "Muloqot" },
  { arabic: "بِخَيْر", transliteration: "Bikhayr", uzbek: "Yaxshi", category: "Muloqot" },
  { arabic: "إِلَى اللِّقَاء", transliteration: "Ila al-liqa", uzbek: "Ko'rishguncha", category: "Muloqot" },
  { arabic: "مَعَ السَّلَامَة", transliteration: "Ma'a as-salamah", uzbek: "Xayr", category: "Muloqot" },

  // Uy (Home)
  { arabic: "بَيْت", transliteration: "Bayt", uzbek: "Uy", category: "Uy" },
  { arabic: "بَاب", transliteration: "Bab", uzbek: "Eshik", category: "Uy" },
  { arabic: "نَافِذَة", transliteration: "Nafidhah", uzbek: "Deraza", category: "Uy" },
  { arabic: "غُرْفَة", transliteration: "Ghurfah", uzbek: "Xona", category: "Uy" },
  { arabic: "مَطْبَخ", transliteration: "Matbakh", uzbek: "Oshxona", category: "Uy" },
  { arabic: "حَمَّام", transliteration: "Hammam", uzbek: "Hammom", category: "Uy" },
  { arabic: "سَرِير", transliteration: "Sarir", uzbek: "Karavot", category: "Uy" },
  { arabic: "طَاوِلَة", transliteration: "Tawilah", uzbek: "Stol", category: "Uy" },
  { arabic: "كُرْسِيّ", transliteration: "Kursiyy", uzbek: "Stul", category: "Uy" },
  { arabic: "مِصْبَاح", transliteration: "Misbah", uzbek: "Chiroq", category: "Uy" },

  // Tabiat (Nature)
  { arabic: "شَمْس", transliteration: "Shams", uzbek: "Quyosh", category: "Tabiat" },
  { arabic: "قَمَر", transliteration: "Qamar", uzbek: "Oy", category: "Tabiat" },
  { arabic: "سَمَاء", transliteration: "Sama'", uzbek: "Osmon", category: "Tabiat" },
  { arabic: "أَرْض", transliteration: "Ard", uzbek: "Yer", category: "Tabiat" },
  { arabic: "مَاء", transliteration: "Ma'", uzbek: "Suv", category: "Tabiat" },
  { arabic: "نَار", transliteration: "Nar", uzbek: "Olov", category: "Tabiat" },
  { arabic: "شَجَرَة", transliteration: "Shajarah", uzbek: "Daraxt", category: "Tabiat" },
  { arabic: "زَهْرَة", transliteration: "Zahrah", uzbek: "Gul", category: "Tabiat" },
  { arabic: "بَحْر", transliteration: "Bahr", uzbek: "Dengiz", category: "Tabiat" },
  { arabic: "جَبَل", transliteration: "Jabal", uzbek: "Tog'", category: "Tabiat" },

  // Ranglar (Colors)
  { arabic: "أَبْيَض", transliteration: "Abyad", uzbek: "Oq", category: "Ranglar" },
  { arabic: "أَسْوَد", transliteration: "Aswad", uzbek: "Qora", category: "Ranglar" },
  { arabic: "أَحْمَر", transliteration: "Ahmar", uzbek: "Qizil", category: "Ranglar" },
  { arabic: "أَزْرَق", transliteration: "Azraq", uzbek: "Ko'k", category: "Ranglar" },
  { arabic: "أَخْضَر", transliteration: "Akhdar", uzbek: "Yashil", category: "Ranglar" },
  { arabic: "أَصْفَر", transliteration: "Asfar", uzbek: "Sariq", category: "Ranglar" },

  // Sonlar (Numbers)
  { arabic: "وَاحِد", transliteration: "Wahid", uzbek: "Bir", category: "Sonlar" },
  { arabic: "اِثْنَان", transliteration: "Ithnan", uzbek: "Ikki", category: "Sonlar" },
  { arabic: "ثَلَاثَة", transliteration: "Thalathah", uzbek: "Uch", category: "Sonlar" },
  { arabic: "أَرْبَعَة", transliteration: "Arba'ah", uzbek: "To'rt", category: "Sonlar" },
  { arabic: "خَمْسَة", transliteration: "Khamsah", uzbek: "Besh", category: "Sonlar" },
  { arabic: "سِتَّة", transliteration: "Sittah", uzbek: "Olti", category: "Sonlar" },
  { arabic: "سَبْعَة", transliteration: "Sab'ah", uzbek: "Yetti", category: "Sonlar" },
  { arabic: "ثَمَانِيَة", transliteration: "Thamaniyah", uzbek: "Sakkiz", category: "Sonlar" },
  { arabic: "تِسْعَة", transliteration: "Tis'ah", uzbek: "To'qqiz", category: "Sonlar" },
  { arabic: "عَشَرَة", transliteration: "Asharah", uzbek: "O'n", category: "Sonlar" },

  // Vaqt (Time)
  { arabic: "يَوْم", transliteration: "Yawm", uzbek: "Kun", category: "Vaqt" },
  { arabic: "أُسْبُوع", transliteration: "Usbu'", uzbek: "Hafta", category: "Vaqt" },
  { arabic: "شَهْر", transliteration: "Shahr", uzbek: "Oy", category: "Vaqt" },
  { arabic: "سَنَة", transliteration: "Sanah", uzbek: "Yil", category: "Vaqt" },
  { arabic: "سَاعَة", transliteration: "Sa'ah", uzbek: "Soat", category: "Vaqt" },
  { arabic: "دَقِيقَة", transliteration: "Daqiqah", uzbek: "Daqiqa", category: "Vaqt" },
  { arabic: "صَبَاح", transliteration: "Sabah", uzbek: "Ertalab", category: "Vaqt" },
  { arabic: "مَسَاء", transliteration: "Masa'", uzbek: "Kechqurun", category: "Vaqt" },
  { arabic: "لَيْل", transliteration: "Layl", uzbek: "Tun", category: "Vaqt" },

  // Ovqat (Food)
  { arabic: "خُبْز", transliteration: "Khubz", uzbek: "Non", category: "Ovqat" },
  { arabic: "لَحْم", transliteration: "Lahm", uzbek: "Go'sht", category: "Ovqat" },
  { arabic: "أَرُزّ", transliteration: "Aruzz", uzbek: "Guruch", category: "Ovqat" },
  { arabic: "حَلِيب", transliteration: "Halib", uzbek: "Sut", category: "Ovqat" },
  { arabic: "شَاي", transliteration: "Shay", uzbek: "Choy", category: "Ovqat" },
  { arabic: "قَهْوَة", transliteration: "Qahwah", uzbek: "Qahva", category: "Ovqat" },
  { arabic: "تُفَّاح", transliteration: "Tuffah", uzbek: "Olma", category: "Ovqat" },
  { arabic: "مَوْز", transliteration: "Mawz", uzbek: "Banan", category: "Ovqat" },
  { arabic: "بُرْتُقَال", transliteration: "Burtuqal", uzbek: "Apelsin", category: "Ovqat" },
  { arabic: "عِنَب", transliteration: "Inab", uzbek: "Uzum", category: "Ovqat" },

  // Tan a'zolari (Body parts)
  { arabic: "رَأْس", transliteration: "Ra's", uzbek: "Bosh", category: "Tana" },
  { arabic: "عَيْن", transliteration: "Ayn", uzbek: "Ko'z", category: "Tana" },
  { arabic: "أُذُن", transliteration: "Udhun", uzbek: "Quloq", category: "Tana" },
  { arabic: "أَنْف", transliteration: "Anf", uzbek: "Burun", category: "Tana" },
  { arabic: "فَم", transliteration: "Fam", uzbek: "Og'iz", category: "Tana" },
  { arabic: "يَد", transliteration: "Yad", uzbek: "Qo'l", category: "Tana" },
  { arabic: "رِجْل", transliteration: "Rijl", uzbek: "Oyoq", category: "Tana" },
  { arabic: "قَلْب", transliteration: "Qalb", uzbek: "Yurak", category: "Tana" },

  // Hayvonlar (Animals)
  { arabic: "كَلْب", transliteration: "Kalb", uzbek: "Kuchuk", category: "Hayvonlar" },
  { arabic: "قِطَّة", transliteration: "Qittah", uzbek: "Mushuk", category: "Hayvonlar" },
  { arabic: "حِصَان", transliteration: "Hisan", uzbek: "Ot", category: "Hayvonlar" },
  { arabic: "جَمَل", transliteration: "Jamal", uzbek: "Tuya", category: "Hayvonlar" },
  { arabic: "أَسَد", transliteration: "Asad", uzbek: "Sher", category: "Hayvonlar" },
  { arabic: "طَائِر", transliteration: "Ta'ir", uzbek: "Qush", category: "Hayvonlar" },
  { arabic: "سَمَكَة", transliteration: "Samakah", uzbek: "Baliq", category: "Hayvonlar" },
  { arabic: "فِيل", transliteration: "Fil", uzbek: "Fil", category: "Hayvonlar" },

  // Maktab (School)
  { arabic: "كِتَاب", transliteration: "Kitab", uzbek: "Kitob", category: "Maktab" },
  { arabic: "قَلَم", transliteration: "Qalam", uzbek: "Qalam", category: "Maktab" },
  { arabic: "دَفْتَر", transliteration: "Daftar", uzbek: "Daftar", category: "Maktab" },
  { arabic: "مَدْرَسَة", transliteration: "Madrasah", uzbek: "Maktab", category: "Maktab" },
  { arabic: "مُعَلِّم", transliteration: "Mu'allim", uzbek: "O'qituvchi", category: "Maktab" },
  { arabic: "طَالِب", transliteration: "Talib", uzbek: "Talaba", category: "Maktab" },
  { arabic: "سَبُّورَة", transliteration: "Sabburah", uzbek: "Doska", category: "Maktab" },
  { arabic: "حَقِيبَة", transliteration: "Haqibah", uzbek: "Sumka", category: "Maktab" },

  // Sifatlar (Adjectives)
  { arabic: "كَبِير", transliteration: "Kabir", uzbek: "Katta", category: "Sifatlar" },
  { arabic: "صَغِير", transliteration: "Saghir", uzbek: "Kichik", category: "Sifatlar" },
  { arabic: "جَمِيل", transliteration: "Jamil", uzbek: "Chiroyli", category: "Sifatlar" },
  { arabic: "قَبِيح", transliteration: "Qabih", uzbek: "Xunuk", category: "Sifatlar" },
  { arabic: "طَوِيل", transliteration: "Tawil", uzbek: "Uzun", category: "Sifatlar" },
  { arabic: "قَصِير", transliteration: "Qasir", uzbek: "Qisqa", category: "Sifatlar" },
  { arabic: "جَدِيد", transliteration: "Jadid", uzbek: "Yangi", category: "Sifatlar" },
  { arabic: "قَدِيم", transliteration: "Qadim", uzbek: "Eski", category: "Sifatlar" },
  { arabic: "سَرِيع", transliteration: "Sari'", uzbek: "Tez", category: "Sifatlar" },
  { arabic: "بَطِيء", transliteration: "Bati'", uzbek: "Sekin", category: "Sifatlar" },
  { arabic: "قَوِيّ", transliteration: "Qawiyy", uzbek: "Kuchli", category: "Sifatlar" },
  { arabic: "ضَعِيف", transliteration: "Da'if", uzbek: "Kuchsiz", category: "Sifatlar" },
  { arabic: "غَنِيّ", transliteration: "Ghaniyy", uzbek: "Boy", category: "Sifatlar" },
  { arabic: "فَقِير", transliteration: "Faqir", uzbek: "Kambag'al", category: "Sifatlar" },
  { arabic: "سَعِيد", transliteration: "Sa'id", uzbek: "Baxtli", category: "Sifatlar" },
  { arabic: "حَزِين", transliteration: "Hazin", uzbek: "G'amgin", category: "Sifatlar" },

  // Fe'llar (Verbs)
  { arabic: "ذَهَبَ", transliteration: "Dhahaba", uzbek: "Bormoq", category: "Fe'llar" },
  { arabic: "جَاءَ", transliteration: "Ja'a", uzbek: "Kelmoq", category: "Fe'llar" },
  { arabic: "أَكَلَ", transliteration: "Akala", uzbek: "Yemoq", category: "Fe'llar" },
  { arabic: "شَرِبَ", transliteration: "Shariba", uzbek: "Ichmoq", category: "Fe'llar" },
  { arabic: "نَامَ", transliteration: "Nama", uzbek: "Uxlamoq", category: "Fe'llar" },
  { arabic: "قَرَأَ", transliteration: "Qara'a", uzbek: "O'qimoq", category: "Fe'llar" },
  { arabic: "كَتَبَ", transliteration: "Kataba", uzbek: "Yozmoq", category: "Fe'llar" },
  { arabic: "فَهِمَ", transliteration: "Fahima", uzbek: "Tushunmoq", category: "Fe'llar" },
  { arabic: "عَلِمَ", transliteration: "Alima", uzbek: "Bilmoq", category: "Fe'llar" },
  { arabic: "عَمِلَ", transliteration: "Amila", uzbek: "Ishlamoq", category: "Fe'llar" },
  { arabic: "جَلَسَ", transliteration: "Jalasa", uzbek: "O'tirmoq", category: "Fe'llar" },
  { arabic: "قَامَ", transliteration: "Qama", uzbek: "Turmoq", category: "Fe'llar" },
  { arabic: "رَأَى", transliteration: "Ra'a", uzbek: "Ko'rmoq", category: "Fe'llar" },
  { arabic: "سَمِعَ", transliteration: "Sami'a", uzbek: "Eshitmoq", category: "Fe'llar" },
  { arabic: "قَالَ", transliteration: "Qala", uzbek: "Aytmoq", category: "Fe'llar" },
  { arabic: "سَأَلَ", transliteration: "Sa'ala", uzbek: "So'ramoq", category: "Fe'llar" },

  // Joylar (Places)
  { arabic: "مَدِينَة", transliteration: "Madinah", uzbek: "Shahar", category: "Joylar" },
  { arabic: "قَرْيَة", transliteration: "Qaryah", uzbek: "Qishloq", category: "Joylar" },
  { arabic: "مَسْجِد", transliteration: "Masjid", uzbek: "Masjid", category: "Joylar" },
  { arabic: "سُوق", transliteration: "Suq", uzbek: "Bozor", category: "Joylar" },
  { arabic: "مُسْتَشْفَى", transliteration: "Mustashfa", uzbek: "Kasalxona", category: "Joylar" },
  { arabic: "مَطَار", transliteration: "Matar", uzbek: "Aeroport", category: "Joylar" },
  { arabic: "حَدِيقَة", transliteration: "Hadiqah", uzbek: "Bog'", category: "Joylar" },
  { arabic: "مَكْتَب", transliteration: "Maktab", uzbek: "Ofis", category: "Joylar" },

  // Kasblar (Professions)
  { arabic: "طَبِيب", transliteration: "Tabib", uzbek: "Shifokor", category: "Kasblar" },
  { arabic: "مُهَنْدِس", transliteration: "Muhandis", uzbek: "Muhandis", category: "Kasblar" },
  { arabic: "طَيَّار", transliteration: "Tayyar", uzbek: "Uchuvchi", category: "Kasblar" },
  { arabic: "شُرْطِيّ", transliteration: "Shurtiyy", uzbek: "Politsiyachi", category: "Kasblar" },
  { arabic: "فَلَّاح", transliteration: "Fallah", uzbek: "Dehqon", category: "Kasblar" },
  { arabic: "تَاجِر", transliteration: "Tajir", uzbek: "Savdogar", category: "Kasblar" },
  { arabic: "طَبَّاخ", transliteration: "Tabbakh", uzbek: "Oshpaz", category: "Kasblar" },
  { arabic: "خَيَّاط", transliteration: "Khayyat", uzbek: "Tikuvchi", category: "Kasblar" },

  // Kiyimlar (Clothes)
  { arabic: "قَمِيص", transliteration: "Qamis", uzbek: "Ko'ylak", category: "Kiyimlar" },
  { arabic: "سِرْوَال", transliteration: "Sirwal", uzbek: "Shim", category: "Kiyimlar" },
  { arabic: "فُسْتَان", transliteration: "Fustan", uzbek: "Ko'ylak (ayollar)", category: "Kiyimlar" },
  { arabic: "حِذَاء", transliteration: "Hidha'", uzbek: "Oyoq kiyim", category: "Kiyimlar" },
  { arabic: "قُبَّعَة", transliteration: "Qubba'ah", uzbek: "Shlyapa", category: "Kiyimlar" },
  { arabic: "نَظَّارَة", transliteration: "Nazzarah", uzbek: "Ko'zoynak", category: "Kiyimlar" },

  // Transport
  { arabic: "سَيَّارَة", transliteration: "Sayyarah", uzbek: "Mashina", category: "Transport" },
  { arabic: "حَافِلَة", transliteration: "Hafilah", uzbek: "Avtobus", category: "Transport" },
  { arabic: "دَرَّاجَة", transliteration: "Darrajah", uzbek: "Velosiped", category: "Transport" },
  { arabic: "قِطَار", transliteration: "Qitar", uzbek: "Poezd", category: "Transport" },
  { arabic: "طَائِرَة", transliteration: "Ta'irah", uzbek: "Samolyot", category: "Transport" },
  { arabic: "سَفِينَة", transliteration: "Safinah", uzbek: "Kema", category: "Transport" },

  // Diniy (Religious)
  { arabic: "اللَّه", transliteration: "Allah", uzbek: "Alloh", category: "Din" },
  { arabic: "رَسُول", transliteration: "Rasul", uzbek: "Payg'ambar", category: "Din" },
  { arabic: "قُرْآن", transliteration: "Qur'an", uzbek: "Qur'on", category: "Din" },
  { arabic: "إِيمَان", transliteration: "Iman", uzbek: "Iymon", category: "Din" },
  { arabic: "صَلَاة", transliteration: "Salah", uzbek: "Namoz", category: "Din" },
  { arabic: "صَوْم", transliteration: "Sawm", uzbek: "Ro'za", category: "Din" },
  { arabic: "زَكَاة", transliteration: "Zakah", uzbek: "Zakot", category: "Din" },
  { arabic: "حَجّ", transliteration: "Hajj", uzbek: "Haj", category: "Din" },
  { arabic: "جَنَّة", transliteration: "Jannah", uzbek: "Jannat", category: "Din" },
  { arabic: "نَار", transliteration: "Nar", uzbek: "Do'zax", category: "Din" },
  { arabic: "مَلَك", transliteration: "Malak", uzbek: "Farishta", category: "Din" },
  { arabic: "دُعَاء", transliteration: "Du'a", uzbek: "Duo", category: "Din" },

  // Qo'shimcha (Extra)
  { arabic: "مُشْكِلَة", transliteration: "Mushkilah", uzbek: "Muammo", category: "Boshqa" },
  { arabic: "حَلّ", transliteration: "Hall", uzbek: "Yechim", category: "Boshqa" },
  { arabic: "فِكْرَة", transliteration: "Fikrah", uzbek: "G'oya", category: "Boshqa" },
  { arabic: "سُؤَال", transliteration: "Su'al", uzbek: "Savol", category: "Boshqa" },
  { arabic: "جَوَاب", transliteration: "Jawab", uzbek: "Javob", category: "Boshqa" },
  { arabic: "مَوْضُوع", transliteration: "Mawdu'", uzbek: "Mavzu", category: "Boshqa" },
  { arabic: "قِصَّة", transliteration: "Qissah", uzbek: "Hikoya", category: "Boshqa" },
  { arabic: "خَبَر", transliteration: "Khabar", uzbek: "Xabar", category: "Boshqa" },
  { arabic: "رِسَالَة", transliteration: "Risalah", uzbek: "Xat", category: "Boshqa" },
  { arabic: "هَاتِف", transliteration: "Hatif", uzbek: "Telefon", category: "Boshqa" },
  { arabic: "حَاسُوب", transliteration: "Hasub", uzbek: "Kompyuter", category: "Boshqa" },
  { arabic: "تِلْفَاز", transliteration: "Tilfaz", uzbek: "Televizor", category: "Boshqa" },
];
